server:
  port: 9000
  servlet:
    context-path: /member

spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/train_member?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:/mapper/**/*.xml

logging:
  level:
    "[com.hedon.train.member.mapper]": trace
